channels: !!python/tuple
- defaults
dependencies:
- alabaster=0.7.10=py35_0
- babel=2.3.4=py35_0
- bokeh=0.12.4=py35_0
- cycler=0.10.0=py35_0
- cython=0.25.2=py35_0
- decorator=4.0.11=py35_0
- docutils=0.13.1=py35_0
- freetype=2.5.5=2
- icu=54.1=0
- imagesize=0.7.1=py35_0
- ipython=5.3.0=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.9.5=py35_0
- libpng=1.6.27=0
- markupsafe=0.23=py35_2
- matplotlib=2.0.0=np112py35_0
- mkl=2017.0.1=0
- mpmath=0.19=py35_1
- nose=1.3.7=py35_1
- numpy=1.12.0=py35_0
- openssl=1.0.2k=1
- path.py=10.1=py35_0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- ply=3.10=py35_0
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- py=1.4.32=py35_0
- pygments=2.2.0=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_2
- pytest=3.0.6=py35_0
- python=3.5.3=1
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pyyaml=3.12=py35_0
- qt=5.6.2=0
- readline=6.2=2
- requests=2.13.0=py35_0
- scipy=0.18.1=np112py35_1
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.5.1=py35_0
- sqlite=3.13.0=0
- sympy=1.0=py35_0
- tk=8.5.18=0
- tornado=4.4.2=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - prompt-toolkit==1.0.9
  - better_apidoc==0.1.2
